<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Calendar, CircleCheck, Warning, TrendCharts, ArrowRight, Clock } from '@element-plus/icons-vue'
import api, { unwrap } from '../api'
import { useAuthStore } from '../store'

const auth=useAuthStore();const router=useRouter();const data=ref({tasks:[],stats:{},users:[],milestones:[]});const loading=ref(true)
const firstName=computed(()=>auth.user?.name||'')
const statusText={todo:'未完成',doing:'未完成',verify:'未完成',done:'完成'}
const priorityType={P0:'danger',P1:'warning',P2:'primary',P3:'info'}
const today=new Date().toISOString().slice(0,10);const selectedDate=ref(today)
const weekDates=computed(()=>{const now=new Date();const day=now.getDay()||7;const monday=new Date(now);monday.setDate(now.getDate()-day+1);return Array.from({length:7},(_,i)=>{const date=new Date(monday);date.setDate(monday.getDate()+i);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;return{key,label:`周${'一二三四五六日'[i]}`,date:`${date.getMonth()+1}/${date.getDate()}`,today:key===today}})})
const selectedDayTasks=computed(()=>data.value.tasks.filter(t=>t.dueDate===selectedDate.value).sort((a,b)=>(a.startTime||'99:99').localeCompare(b.startTime||'99:99')))
const selectedDayLabel=computed(()=>weekDates.value.find(d=>d.key===selectedDate.value))
onMounted(async()=>{try{data.value=unwrap(await api.get('/dashboard'))}finally{loading.value=false}})
</script>

<template><div class="page dashboard" v-loading="loading"><section class="welcome-band"><div><p class="eyebrow">{{auth.user?.role==='mentor'?'导师工作台':'学员工作台'}}</p><h1>{{firstName}}，{{new Date().getHours()<12?'上午好':'下午好'}}</h1><p>{{auth.user?.role==='mentor'?'查看学员本周安排，及时完成任务核销与辅导。':`您的师父是${auth.user?.mentor}，今天继续把每一步做扎实。`}}</p></div><div class="weather"><span class="weather-icon">晴</span><div><b>25°C</b><small>广州 · 空气质量良</small></div></div></section>
<section class="stat-grid"><article><div class="stat-icon blue"><el-icon><Calendar/></el-icon></div><div><span>全部任务</span><b>{{data.stats.total||0}}</b><small>本周期任务总量</small></div></article><article><div class="stat-icon green"><el-icon><CircleCheck/></el-icon></div><div><span>已完成</span><b>{{data.stats.completed||0}}</b><small>成果已核销归档</small></div></article><article><div class="stat-icon orange"><el-icon><TrendCharts/></el-icon></div><div><span>综合进度</span><b>{{data.stats.progress||0}}%</b><small>任务平均完成度</small></div></article><article><div class="stat-icon red"><el-icon><Warning/></el-icon></div><div><span>今日到期</span><b>{{data.stats.due||0}}</b><small>请优先关注</small></div></article></section>
<section class="panel switch-schedule"><div class="panel-head"><div><h2>本周日程</h2><p>选择日期查看当日安排，数据来自任务列表</p></div><el-button text type="primary" @click="router.push('/tasks')">管理任务 <el-icon><ArrowRight/></el-icon></el-button></div><div class="week-switch"><button v-for="day in weekDates" :key="day.key" :class="{active:selectedDate===day.key,today:day.today}" @click="selectedDate=day.key"><b>{{day.label}}</b><span>{{day.date}}</span><em>{{data.tasks.filter(t=>t.dueDate===day.key).length}}项</em></button></div><div class="selected-day-head"><div><b>{{selectedDayLabel?.label}} · {{selectedDayLabel?.date}}</b><span>{{selectedDayTasks.length}} 项安排</span></div><div class="schedule-legend"><span class="meeting">会议任务</span><span class="project">项目工作</span><span class="daily">日常工作</span></div></div><div class="day-agenda"><article v-for="task in selectedDayTasks" :key="task.id" :class="task.workCategory"><div class="agenda-time"><b>{{task.startTime||'待定'}}</b><span>{{task.endTime||''}}</span></div><div class="agenda-line"></div><div class="agenda-main"><div><el-tag :type="priorityType[task.priority]" size="small" effect="dark">{{task.priority}}</el-tag><span class="agenda-kind">{{task.workCategory==='meeting'?'会议任务':task.workCategory==='project'?'项目工作':'日常工作'}}</span></div><h3>{{task.title}}</h3><p>{{task.assignee}} · {{task.projectName}} · {{task.method}}</p></div><div class="agenda-progress"><el-progress :percentage="task.progress" :stroke-width="7"/><span class="status" :class="task.status">{{statusText[task.status]}}</span></div></article><el-empty v-if="!selectedDayTasks.length" description="当天暂无任务安排"/></div></section>
<section class="dashboard-grid"><div class="panel task-panel"><div class="panel-head"><div><h2>{{auth.user?.role==='mentor'?'学员任务动态':'近期任务'}}</h2><p>按优先级跟踪执行与核销状态</p></div><el-button text type="primary" @click="router.push('/tasks')">全部任务 <el-icon><ArrowRight/></el-icon></el-button></div><div class="task-list"><div v-for="task in data.tasks.slice(0,5)" :key="task.id" class="task-row"><el-tag :type="priorityType[task.priority]" effect="dark" size="small">{{task.priority}}</el-tag><div class="task-main"><b>{{task.title}}</b><span>{{task.assignee}} · {{task.workCategory==='meeting'?'会议任务':task.projectName}}</span></div><div class="task-progress"><el-progress :percentage="task.progress" :stroke-width="7" :show-text="false"/><span>{{task.progress}}%</span></div><span class="status" :class="task.status">{{statusText[task.status]}}</span></div></div></div><div class="panel quick-panel"><div class="panel-head"><div><h2>快捷入口</h2><p>常用工作一步直达</p></div></div><div class="quick-grid"><button @click="router.push('/smart-input')"><span class="quick-icon blue">AI</span><b>智能拆解</b><small>纪要转行动项</small></button><button @click="router.push('/work-library')"><span class="quick-icon green">报</span><b>周报智写</b><small>成果自动聚合</small></button><button @click="router.push('/growth')"><span class="quick-icon orange">长</span><b>成长档案</b><small>积分与里程碑</small></button><button @click="router.push('/care')"><span class="quick-icon cyan">心</span><b>人文关怀</b><small>情绪与问候</small></button></div></div><div class="panel timeline-panel"><div class="panel-head"><div><h2>成长里程碑</h2><p>每一次完成都有迹可循</p></div></div><div class="timeline"><div v-for="item in data.milestones.filter(m=>m.userId===(auth.user?.role==='mentor'?1:auth.user?.id)).slice(-4).reverse()" :key="item.id" class="timeline-item"><span></span><div><b>{{item.title}}</b><p>{{item.description}}</p><small><el-icon><Clock/></el-icon>{{item.date}}</small></div></div></div></div><div class="panel mentor-card"><p class="eyebrow">师徒关系</p><h2>{{auth.user?.role==='mentor'?'以经验点亮成长':`${auth.user?.mentor} · 我的师父`}}</h2><p>{{auth.user?.goal}}</p><div class="mentor-quote">“把规范做到习惯，把每次复盘变成下一次进步。”</div></div></section></div></template>

