<script setup>
import { onMounted, ref } from 'vue'
import { Trophy, Medal, Calendar, Aim } from '@element-plus/icons-vue'
import api,{unwrap} from '../api'
const data=ref({points:0,rank:'星星',next:100,percent:0,weights:{},milestones:[],tasks:[]})
onMounted(async()=>data.value=unwrap(await api.get('/growth')))
</script>
<template><div class="page"><div class="page-title"><div><p class="eyebrow">GROWTH RECORD</p><h1>成长档案</h1><p>工作进度自动量化为积分，记录师徒共同走过的每一步</p></div></div><section class="growth-hero"><div class="rank-emblem"><el-icon><Trophy/></el-icon><span>{{data.rank}}</span></div><div class="growth-main"><p>当前成长等级</p><h2>{{data.rank}} · {{data.points}} 积分</h2><el-progress :percentage="data.percent" :stroke-width="12" color="#ff7a00"/><small>距离下一阶段还需 {{Math.max(0,data.next-data.points)}} 积分</small></div><div class="rank-path"><div class="done">星星<small>0</small></div><i></i><div :class="{done:data.points>=100}">月亮<small>100</small></div><i></i><div :class="{done:data.points>=300}">太阳<small>300</small></div><i></i><div :class="{done:data.points>=600}">皇冠<small>600</small></div></div></section><div class="growth-grid"><section class="panel"><div class="panel-head"><div><h2>进度构成</h2><p>按业务数据实时加权计算</p></div></div><div class="weight-list"><div v-for="(v,k) in data.weights" :key="k"><span>{{{schedule:'个人日程',meeting:'会议行动项',practice:'实操记录',supplement:'补充材料'}[k]}}</span><el-progress :percentage="v" :stroke-width="9"/><b>{{v}}%</b></div></div></section><section class="panel achievement-panel"><div class="panel-head"><div><h2>已获成就</h2><p>完成关键行动自动解锁</p></div></div><div class="badges"><div><span><el-icon><Medal/></el-icon></span><b>学习之星</b><small>完成阶段学习</small></div><div><span><el-icon><Aim/></el-icon></span><b>任务达人</b><small>任务按期核销</small></div><div><span><el-icon><Calendar/></el-icon></span><b>协作先锋</b><small>主动协同支持</small></div></div></section><section class="panel milestone-panel"><div class="panel-head"><div><h2>成长时间线</h2><p>任务、技能与导师评价统一沉淀</p></div></div><el-timeline><el-timeline-item v-for="item in data.milestones.slice().reverse()" :key="item.id" :timestamp="item.date" color="#00a650"><h3>{{item.title}}</h3><p>{{item.description}}</p><el-tag size="small" effect="plain">{{item.type}}</el-tag></el-timeline-item></el-timeline></section></div></div></template>

