<script setup>
import { computed,ref } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import { UploadFilled,MagicStick,Delete,Check } from '@element-plus/icons-vue'
import api,{errorText,unwrap} from '../api'

const text=ref('');const fileName=ref('');const tasks=ref([]);const loading=ref(false);const publishing=ref(false);const warning=ref('');const desensConfirmed=ref(false);const sourceType=ref('meeting');const methods=ref(['WBS'])
const methodOptions=[{value:'四象限法',label:'四象限法',desc:'按重要性与紧急性确定优先级'},{value:'WBS',label:'WBS 工作分解',desc:'拆分工作包、依赖和交付物'},{value:'KANO',label:'KANO 模型',desc:'识别基本、期望与魅力需求'},{value:'RICE',label:'RICE 评分',desc:'综合影响、信心和成本排序'},{value:'关键路径法',label:'关键路径法',desc:'识别依赖和最短完工路径'},{value:'SMART',label:'SMART 目标法',desc:'确保任务具体且可衡量'}]
const selectedCount=computed(()=>tasks.value.filter(t=>t.selected&&!t.published&&!t.duplicate).length)
const sourceDefaults=computed(()=>sourceType.value==='meeting'?{workCategory:'meeting',projectName:'会议行动项',source:'会议导入'}:sourceType.value==='project'?{workCategory:'project',projectName:'待命名项目',source:'项目资料导入'}:{workCategory:'daily',projectName:'日常工作',source:'日程导入'})
async function uploadFile(options){const fd=new FormData();fd.append('file',options.file.raw||options.file);try{const data=unwrap(await api.post('/file/upload',fd));if(!data.content||data.content.length<5){ElMessage.warning('文件内容为空或无法提取文本，请检查文件格式或直接粘贴文本');return}text.value=data.content;fileName.value=data.fileName;desensConfirmed.value=false;ElMessage.success('内容已提取并自动脱敏，请人工复核')}catch(e){ElMessage.error(errorText(e))}}
async function desensitize(){if(!text.value)return ElMessage.warning('请先输入内容');text.value=unwrap(await api.post('/desensitize',{text:text.value})).text;desensConfirmed.value=false;ElMessage.success('已重新脱敏，请人工确认')}
async function confirmDesens(){if(!text.value.trim())return ElMessage.warning('请先导入或输入内容');await ElMessageBox.confirm('请确认手机号、证件号、邮箱、地址、密码及密钥等敏感信息均已正确隐藏。','脱敏人工复核',{confirmButtonText:'确认脱敏无误',cancelButtonText:'继续检查',type:'warning'});desensConfirmed.value=true;ElMessage.success('已完成脱敏确认')}
async function split(){if(text.value.trim().length<10)return ElMessage.warning('请至少输入10个字');if(!desensConfirmed.value)return ElMessage.warning('请先完成人工脱敏确认');if(!methods.value.length)return ElMessage.warning('至少选择一种拆解方法');if(/未配置|音频文件|图片文件|离线展示/.test(text.value))return ElMessage.warning('当前文本是提示信息而非文件内容，请先粘贴或输入实际文本');loading.value=true;warning.value='';try{const data=unwrap(await api.post('/task/split',{text:text.value,methods:methods.value}));tasks.value=data.tasks.map((task,i)=>({...task,...sourceDefaults.value,startTime:`${String(Math.min(17,9+i)).padStart(2,'0')}:00`,endTime:`${String(Math.min(18,10+i)).padStart(2,'0')}:00`,selected:true,published:false,duplicate:false}));warning.value=data.warning||''}catch(e){ElMessage.error(errorText(e))}finally{loading.value=false}}
async function publishSelected(){const selected=tasks.value.filter(t=>t.selected&&!t.published&&!t.duplicate);if(!selected.length)return ElMessage.warning('请勾选至少一项未发布任务');publishing.value=true;try{const data=unwrap(await api.post('/tasks/bulk',{tasks:selected.map(t=>({...t,assigneeId:1,points:60}))}));const published=new Set(data.published.map(t=>t.title));const duplicates=new Set(data.duplicates.map(t=>t.title));tasks.value.forEach(t=>{if(published.has(t.title)){t.published=true;t.selected=false}if(duplicates.has(t.title)){t.duplicate=true;t.selected=false}});if(data.published.length)ElMessage.success(`成功发布 ${data.published.length} 项任务`);if(data.duplicates.length)ElMessage.warning(`${data.duplicates.length} 项重复任务已跳过`)}catch(e){ElMessage.error(errorText(e))}finally{publishing.value=false}}
</script>

<template><div class="page"><div class="page-title"><div><p class="eyebrow">MULTIMODAL AI</p><h1>智能输入与任务拆解</h1><p>先标记材料来源，会议导入任务将独立归类</p></div></div><div class="step-line"><div class="active"><b>1</b><span>选择来源并导入</span></div><i></i><div :class="{active:desensConfirmed}"><b>2</b><span>复核脱敏</span></div><i></i><div :class="{active:tasks.length}"><b>3</b><span>拆解发布</span></div></div>
<div class="source-type-bar"><div><b>材料来源</b><span>决定任务中心的上级分类</span></div><el-radio-group v-model="sourceType"><el-radio-button value="meeting">会议纪要/录音</el-radio-button><el-radio-button value="project">项目资料</el-radio-button><el-radio-button value="daily">日程/日常材料</el-radio-button></el-radio-group></div>
<div class="smart-layout"><section class="panel input-panel"><div class="panel-head"><div><h2>源文件与文本</h2><p>支持 Word、Excel、TXT、CSV、音频和图片</p></div></div><el-upload drag action="#" :show-file-list="false" :http-request="uploadFile" accept=".doc,.docx,.xls,.xlsx,.txt,.csv,.mp3,.wav,.m4a,.aac,.png,.jpg,.jpeg,.bmp"><el-icon class="el-icon--upload"><UploadFilled/></el-icon><div class="el-upload__text">拖拽文件到此处，或<em>选择文件</em></div><template #tip><div class="el-upload__tip">单文件不超过20MB，上传后需确认脱敏结果</div></template></el-upload><div v-if="fileName" class="file-chip"><el-icon><Check/></el-icon>{{fileName}}</div><el-input v-model="text" type="textarea" :rows="9" placeholder="也可以直接粘贴会议纪要、项目资料或日程..." @input="desensConfirmed=false"/><div class="desens-review" :class="{confirmed:desensConfirmed}"><div><b>{{desensConfirmed?'已确认脱敏结果':'等待人工脱敏确认'}}</b><p>确认手机、证件、邮箱、姓名、地址及密码/密钥均已隐藏。</p></div><el-button :type="desensConfirmed?'success':'warning'" plain @click="confirmDesens">{{desensConfirmed?'重新确认':'检查并确认'}}</el-button></div><div class="method-picker"><div><b>科学拆解方法</b><small>可多选组合使用</small></div><el-checkbox-group v-model="methods"><el-checkbox v-for="item in methodOptions" :key="item.value" :value="item.value"><span>{{item.label}}</span><small>{{item.desc}}</small></el-checkbox></el-checkbox-group></div><div class="input-actions"><el-button :icon="Delete" @click="text='';tasks=[];desensConfirmed=false">清空</el-button><el-button @click="desensitize">重新脱敏</el-button><el-button type="primary" :icon="MagicStick" :loading="loading" :disabled="!desensConfirmed" @click="split">确认并智能拆解</el-button></div></section>
<section class="panel result-panel"><div class="panel-head"><div><h2>结构化任务</h2><p>{{sourceType==='meeting'?'将发布到“会议任务”分类':'勾选需要的任务后一次发布'}}</p></div><div class="result-actions"><el-tag v-if="tasks.length" type="success">{{tasks.length}} 项</el-tag><el-button v-if="tasks.length" type="primary" :disabled="!selectedCount" :loading="publishing" @click="publishSelected">一键发布所选（{{selectedCount}}）</el-button></div></div><el-alert v-if="warning" :title="warning" type="warning" show-icon :closable="false"/><div v-if="tasks.length" class="split-list"><article v-for="(task,i) in tasks" :key="i" :class="{published:task.published,duplicate:task.duplicate}"><el-checkbox v-model="task.selected" :disabled="task.published||task.duplicate"/><div class="split-no">{{String(i+1).padStart(2,'0')}}</div><div class="split-content"><div class="split-title-row"><el-input v-model="task.title" class="title-input" :disabled="task.published"/><el-tag v-if="task.published" type="success" size="small">已发布</el-tag><el-tag v-if="task.duplicate" type="warning" size="small">重复，已跳过</el-tag></div><el-input v-model="task.description" type="textarea" :rows="2" :disabled="task.published"/><div class="split-fields"><el-select v-model="task.priority"><el-option v-for="p in ['P1','P2']" :key="p" :value="p"/></el-select><el-date-picker v-model="task.dueDate" value-format="YYYY-MM-DD"/><el-input v-model="task.standard" placeholder="完成标准"/></div><div class="task-classify"><el-select v-model="task.workCategory"><el-option label="会议任务" value="meeting"/><el-option label="项目工作" value="project"/><el-option label="日常工作" value="daily"/></el-select><el-input v-model="task.projectName" placeholder="会议/项目/工作名称"/><el-time-select v-model="task.startTime" start="08:00" step="00:30" end="18:00"/><el-time-select v-model="task.endTime" start="08:30" step="00:30" end="19:00"/></div><small class="method-used">采用：{{task.method}}</small></div></article></div><el-empty v-else description="完成脱敏复核后，拆解结果将在这里显示"/></section></div></div></template>

