<script setup>
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { UploadFilled, Download, Files, Scissor } from '@element-plus/icons-vue'
import api,{errorText,unwrap} from '../api'
const files=ref([]);const loading=ref(false)
function change(_file,list){files.value=list}
async function merge(){if(files.value.length<2)return ElMessage.warning('请至少选择2个PDF文件');loading.value=true;const fd=new FormData();files.value.forEach(f=>fd.append('files',f.raw));try{const res=await api.post('/pdf/merge',fd,{responseType:'blob'});const url=URL.createObjectURL(res.data);const a=document.createElement('a');a.href=url;a.download='合并文件.pdf';a.click();URL.revokeObjectURL(url);ElMessage.success('PDF合并完成')}catch(e){ElMessage.error(errorText(e))}finally{loading.value=false}}

const splitFile=ref(null);const splitRanges=ref('');const splitLoading=ref(false);const splitPageCount=ref(0);const splitFileName=ref('')
async function onSplitChange(file){if(!file.raw)return;splitFile.value=file.raw;splitFileName.value=file.name;splitPageCount.value=0;splitRanges.value='';const fd=new FormData();fd.append('file',file.raw);try{const info=unwrap(await api.post('/pdf/info',fd));splitPageCount.value=info.pages;splitRanges.value=`1-${info.pages}`}catch(e){ElMessage.error(errorText(e));splitFile.value=null}}
function onSplitRemove(){splitFile.value=null;splitPageCount.value=0;splitRanges.value='';splitFileName.value=''}
async function splitPdf(){if(!splitFile.value)return ElMessage.warning('请先选择PDF文件');if(!splitRanges.value.trim())return ElMessage.warning('请填写页码范围');splitLoading.value=true;const fd=new FormData();fd.append('file',splitFile.value);fd.append('ranges',splitRanges.value);try{const res=await api.post('/pdf/split',fd,{responseType:'blob'});const url=URL.createObjectURL(res.data);const a=document.createElement('a');a.href=url;a.download=(splitFileName.value.replace(/\.pdf$/i,'')||'document')+'_拆分.pdf';a.click();URL.revokeObjectURL(url);ElMessage.success('PDF拆分完成')}catch(e){let msg=errorText(e);if(e.response?.data instanceof Blob){try{msg=JSON.parse(await e.response.data.text()).message}catch{}}ElMessage.error(msg)}finally{splitLoading.value=false}}
</script><template><div class="page"><div class="page-title"><div><p class="eyebrow">UTILITY TOOLBOX</p><h1>文件百宝箱</h1><p>处理日常工作中常见的 PDF 合并与文件拆分需求</p></div></div><div class="tool-grid"><section class="panel tool-active"><div class="tool-title"><span><el-icon><Files/></el-icon></span><div><h2>PDF 文件合并</h2><p>按列表顺序将多个 PDF 合并为一个文件</p></div></div><el-upload drag multiple accept=".pdf" :auto-upload="false" :on-change="change" :on-remove="change"><el-icon class="el-icon--upload"><UploadFilled/></el-icon><div class="el-upload__text">拖拽多个 PDF 到此处，或<em>选择文件</em></div></el-upload><el-button type="primary" size="large" :icon="Download" :loading="loading" @click="merge">合并并下载</el-button></section><section class="panel tool-active"><div class="tool-title"><span><el-icon><Scissor/></el-icon></span><div><h2>PDF 页面拆分</h2><p>按页码范围提取并生成独立文件</p></div></div><el-upload drag accept=".pdf" :auto-upload="false" :limit="1" :on-change="onSplitChange" :on-remove="onSplitRemove"><el-icon class="el-icon--upload"><UploadFilled/></el-icon><div class="el-upload__text">拖拽 PDF 到此处，或<em>选择文件</em></div><template #tip><div v-if="splitPageCount" class="split-info"><b>{{splitFileName}}</b> 共 <b>{{splitPageCount}}</b> 页</div></template></el-upload><div v-if="splitPageCount" class="split-range-input"><label>页码范围</label><el-input v-model="splitRanges" placeholder="如 1-3,5,7-10" clearable><template #append>共{{splitPageCount}}页</template></el-input><p class="split-hint">支持单页（5）、连续范围（1-3）、混合（1-3,5,7-10），页码从1开始</p></div><el-button type="primary" size="large" :icon="Download" :loading="splitLoading" :disabled="!splitFile.value||!splitPageCount" @click="splitPdf">拆分并下载</el-button></section></div><div class="security-note"><b>文件安全说明</b><p>上传文件仅在本机后端临时处理，完成或失败后立即删除；请勿上传超出工作授权范围的材料。</p></div></div></template>
