<script setup>
import {computed,onMounted,ref,watch} from 'vue'
import {Download,Document,Refresh} from '@element-plus/icons-vue'
import {ElMessage} from 'element-plus'
import api,{errorText,unwrap} from '../api'
const type=ref('周报'),format=ref('docx'),range=ref([]),report=ref(''),meta=ref(null),loading=ref(false),logs=ref([])
const today=()=>new Date().toISOString().slice(0,10);const monday=()=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)}
function autoRange(){const end=today();if(type.value==='日报')range.value=[end,end];else if(type.value==='月报')range.value=[`${end.slice(0,7)}-01`,end];else range.value=[monday(),end]}
watch(type,autoRange,{immediate:true});const totalHours=computed(()=>logs.value.reduce((s,l)=>s+Number(l.hours||0),0))
async function load(){logs.value=unwrap(await api.get('/work-logs'))}
async function oneClick(){loading.value=true;try{const result=unwrap(await api.post('/reports/generate',{type:type.value,start:range.value[0],end:range.value[1]}));report.value=result.content;meta.value=result;const response=await api.post('/reports/export',{content:report.value,format:format.value,title:`${range.value[1]}_${type.value}`},{responseType:'blob'});const url=URL.createObjectURL(response.data),a=document.createElement('a');a.href=url;a.download=`${range.value[1]}_${type.value}.${format.value}`;a.click();URL.revokeObjectURL(url);ElMessage.success('已自动取数、生成并导出')}catch(e){ElMessage.error(errorText(e))}finally{loading.value=false}}
onMounted(load)
</script>
<template><div class="page autowork"><div class="page-title"><div><p class="eyebrow">AUTO REPORTING</p><h1>工作成果与自动报告</h1><p>系统直接汇总期限内任务和工作记录，一键形成可交付材料</p></div><div class="work-mini"><span>工作记录<b>{{logs.length}}</b></span><span>累计工时<b>{{totalHours}}</b></span></div></div><section class="report-runner"><div class="runner-title"><Document/><div><h2>一键生成与导出</h2><p>选择周期和格式即可，不需要逐条勾选工作</p></div></div><el-segmented v-model="type" :options="['日报','周报','月报','报奖材料']"/><el-date-picker v-model="range" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始" end-placeholder="结束"/><el-segmented v-model="format" :options="[{label:'Word',value:'docx'},{label:'PDF',value:'pdf'},{label:'PPT',value:'pptx'}]"/><el-button type="primary" :icon="Download" :loading="loading" @click="oneClick">一键生成并导出</el-button></section><div class="auto-layout"><section class="auto-preview"><header><div><h2>报告预览</h2><p v-if="meta">已汇总 {{meta.sourceStats.tasks}} 项任务和 {{meta.sourceStats.logs}} 条工作记录</p><p v-else>生成后可继续编辑内容并重新导出</p></div><el-button v-if="report" text :icon="Refresh" @click="oneClick">重新生成</el-button></header><el-alert v-if="meta?.warning" :title="meta.warning" type="warning" :closable="false"/><el-input v-if="report" v-model="report" type="textarea" resize="none"/><el-empty v-else description="尚未生成报告"/></section><section class="fact-stream"><header><h2>自动取数范围</h2><p>任务完成情况会自动进入材料，工作记录作为补充事实</p></header><article v-for="log in logs.slice(0,8)" :key="log.id"><time>{{log.date}}</time><p>{{log.content}}</p><b>{{log.result}}</b></article></section></div></div></template>
<style scoped>
.work-mini{display:flex;gap:9px}.work-mini span{background:#fff;border:1px solid #e4e9ef;padding:9px 13px;font-size:15px;color:#758196}.work-mini b{font-size:19px;color:#087c66;margin-left:8px}.report-runner{display:grid;grid-template-columns:minmax(230px,1fr) auto auto auto auto;align-items:center;gap:12px;background:#fff;border:1px solid #dde5ea;border-left:4px solid #087c66;padding:16px;margin-bottom:14px}.runner-title{display:flex;gap:11px;align-items:center}.runner-title svg{width:27px;color:#087c66}.runner-title h2,.auto-layout h2{font-size:16px;margin:0}.runner-title p,.auto-layout header p{font-size:14px;color:#8190a1;margin:4px 0 0}.auto-layout{display:grid;grid-template-columns:1.7fr .8fr;gap:14px}.auto-preview,.fact-stream{background:#fff;border:1px solid #e4e9ef;padding:18px;min-height:520px}.auto-preview header,.fact-stream header{display:flex;justify-content:space-between;margin-bottom:14px}.auto-preview :deep(textarea){height:430px;line-height:1.75;font-family:inherit}.fact-stream article{padding:12px 0;border-top:1px solid #edf0f4}.fact-stream time{font-size:13px;color:#8793a3}.fact-stream p{font-size:15px;line-height:1.5;margin:5px 0}.fact-stream b{font-size:14px;color:#087c66}@media(max-width:1050px){.report-runner{grid-template-columns:1fr 1fr}.runner-title{grid-column:1/-1}.auto-layout{grid-template-columns:1fr}}@media(max-width:600px){.report-runner{grid-template-columns:1fr}.auto-preview,.fact-stream{min-height:auto}}
.report-runner{display:flex!important;flex-wrap:wrap;min-width:0}.report-runner>.runner-title{flex:1 1 250px}.report-runner>.el-segmented{flex:0 1 auto;max-width:100%;overflow:auto}.report-runner>.el-date-editor{flex:1 1 250px;max-width:360px}.report-runner>.el-button{flex:0 0 auto;margin-left:auto;white-space:nowrap}@media(max-width:680px){.report-runner>*{width:100%!important;max-width:100%!important}.report-runner>.el-button{margin-left:0}.report-runner :deep(.el-segmented){width:100%}}
</style>

