<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Plus, Delete, DocumentCopy, MagicStick } from '@element-plus/icons-vue'
import api,{errorText,unwrap} from '../api'

const logs=ref([]); const report=ref(''); const warning=ref(''); const loading=ref(false); const exporting=ref(false)
const type=ref('周报'); const range=ref([]); const exportFormat=ref('docx')
const form=reactive({date:new Date().toISOString().slice(0,10),hours:1,content:'',result:'',tags:[]})
const totalHours=computed(()=>logs.value.reduce((s,l)=>s+Number(l.hours),0))
async function load(){logs.value=unwrap(await api.get('/work-logs'))}
async function save(){if(!form.content||!form.result)return ElMessage.warning('请填写工作内容和量化成果');await api.post('/work-logs',form);Object.assign(form,{date:new Date().toISOString().slice(0,10),hours:1,content:'',result:'',tags:[]});ElMessage.success('已保存到工作库');load()}
async function remove(id){await api.delete(`/work-logs/${id}`);load()}
async function generate(){loading.value=true;try{const data=unwrap(await api.post('/reports/generate',{type:type.value,start:range.value?.[0],end:range.value?.[1]}));report.value=data.content;warning.value=data.warning||''}catch(e){ElMessage.error(errorText(e))}finally{loading.value=false}}
async function copy(){await navigator.clipboard.writeText(report.value);ElMessage.success('内容已复制')}
async function exportReport(){if(!report.value)return ElMessage.warning('请先生成报告');exporting.value=true;try{const response=await api.post('/reports/export',{content:report.value,format:exportFormat.value,title:`${form.date}_${type.value}`},{responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=`${form.date}_${type.value}.${exportFormat.value}`;a.click();URL.revokeObjectURL(url);ElMessage.success(`${exportFormat.value.toUpperCase()} 文件已生成`)}catch(e){ElMessage.error(errorText(e))}finally{exporting.value=false}}
onMounted(load)
</script>

<template><div class="page"><div class="page-title"><div><p class="eyebrow">WORK ARCHIVE</p><h1>灵枢 · 工作成果聚合器</h1><p>用结构化工作记录生成日报、周报、月报和报奖材料</p></div><div class="library-stats"><span>累计记录<b>{{logs.length}}</b></span><span>投入工时<b>{{totalHours}}</b></span></div></div><div class="library-layout"><section class="left-stack"><div class="panel log-form"><div class="panel-head"><div><h2>记录今日工作</h2><p>成果尽量使用可核验的数字描述</p></div></div><div class="form-grid"><el-date-picker v-model="form.date" value-format="YYYY-MM-DD"/><el-input-number v-model="form.hours" :min="0.5" :step="0.5"/><el-input v-model="form.content" type="textarea" :rows="3" placeholder="完成了什么工作？"/><el-input v-model="form.result" type="textarea" :rows="3" placeholder="取得了什么量化成果？"/></div><el-select v-model="form.tags" multiple allow-create filterable placeholder="添加标签"><el-option v-for="t in ['巡视','安全','学习','会议','协作','检修']" :key="t" :value="t"/></el-select><el-button type="primary" :icon="Plus" @click="save">保存记录</el-button></div><div class="panel history"><div class="panel-head"><div><h2>工作记录</h2><p>按时间倒序沉淀个人成果</p></div></div><article v-for="log in logs" :key="log.id"><div class="log-date"><b>{{log.date.slice(8)}}</b><span>{{log.date.slice(0,7)}}</span></div><div><p>{{log.content}}</p><strong>{{log.result}}</strong><div><el-tag v-for="tag in log.tags" :key="tag" size="small" effect="plain">{{tag}}</el-tag></div></div><el-button text circle :icon="Delete" @click="remove(log.id)"/></article><el-empty v-if="!logs.length" description="暂无记录"/></div></section><section class="panel report-preview"><div class="panel-head"><div><h2>智能材料生成</h2><p>仅基于已记录事实提炼，不虚构数据</p></div><el-button v-if="report" text :icon="DocumentCopy" @click="copy">复制</el-button></div><div class="report-tools"><el-segmented v-model="type" :options="['日报','周报','月报','报奖材料']"/><el-date-picker v-model="range" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/><el-button type="primary" :icon="MagicStick" :loading="loading" @click="generate">生成{{type}}</el-button></div><el-alert v-if="warning" :title="warning" type="warning" :closable="false" show-icon/><div v-if="report" class="export-bar"><div><b>导出材料</b><span>选择格式后生成可下载文件</span></div><el-radio-group v-model="exportFormat" size="small"><el-radio-button value="pdf">PDF</el-radio-button><el-radio-button value="docx">Word</el-radio-button><el-radio-button value="pptx">PPT</el-radio-button></el-radio-group><el-button type="success" :loading="exporting" @click="exportReport">生成并下载</el-button></div><el-input v-if="report" v-model="report" type="textarea" class="report-editor" resize="none"/><el-empty v-else description="选择材料类型和时间范围后开始生成"/></section></div></div></template>

